### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by zethon** [NodeBB-Community/nodebb-plugin-emoji-static#2]
I've tried creating a custom set with a single smiley/emoji in it. My index.json file looks like:

`{ 
    "cwd": "./", 
    "files": "**/*", 
    "ignore": null, 
    "images": 
    [
        { "id": "melvin", "category": "AMB Classic", "width": 24, "height": 18 }
    ]
}`

I've put and the single smiley (melvin.gif) in the same folder. In my config I have:

![image](https://cloud.githubusercontent.com/assets/5203583/16548300/06939572-4158-11e6-9d1d-3dddef81a448.png)

But when I go into the Emoji Extended plugin, I don't see anywhere or how to enable my set.

![image](https://cloud.githubusercontent.com/assets/5203583/16548301/336cb470-4158-11e6-9121-2fd7d8d7f6e0.png)

**Comment by ghost** [comment]
The problem is the format of the `images` property:
It needs to be an object, not an array.
Your sample should look like this:

```
{ "cwd": "./", "files": "**/*", "ignore": null, "images": { "melvin": {"category": "AMB Classic", "width": 24, "height": 18 } } }
```

I also recommend a more restrictive `files` selector or setting `ignore` accordingly since the sample would also match the _index.json_ itself.

**Comment by zethon** [comment]
I corrected my JSON to the following:

`{
        "cwd": "./",
        "files": "**/*",
        "ignore": "index.json",
        "images": {
                "melvin": {
                        "category": "AMB Classic",
                        "width": 24,
                        "height": 18
                }
        }
}`

But I still don't see it. Under "Emoji Extended" I see three options "Global Settings", "Installed Sets" and "Download Plugins". I'm expecting to see something show up under "Installed Sets" but I don't. 

I am a little confused by 'Path to index file (relative to NodeBB root)', but I have tried several different values and none work. For example, I have the smilies in the (full) path '/home/myuser/public_html/nodebb/node_modules/smilies', and I have tried various values such as the full path, and 'node_modules/smilies' and "nodebb/node_modules/smilies', etc.

**Comment by ghost** [comment]
The path needs to reference the file itself (the label seems to be misleading). So, for example, if you want to use an absolute reference: `/home/myuser/public_html/nodebb/node_modules/smilies/index.json`.

**Comment by ghost** [comment]
Once the configuration is working, the set will appear within "Installed Sets", yes.

**Comment by zethon** [comment]
That did it! Thank you very much for your help.
